//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnMuhasebeUygulamasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountMovement
    {
        public int AccountMovementCode { get; set; }
        public Nullable<System.DateTime> MovementDate { get; set; }
        public int SequenceNo { get; set; }
        public string ProcessType { get; set; }
        public string Descript { get; set; }
        public Nullable<double> Debt { get; set; }
        public Nullable<double> Credit { get; set; }
        public string Currency { get; set; }
        public Nullable<int> CurrentCode { get; set; }
    }
}
