//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnMuhasebeUygulamasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdressRegistry
    {
        public int ID { get; set; }
        public string Groupp { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string CompanyTitle { get; set; }
        public Nullable<int> PhoneNo { get; set; }
        public string Province { get; set; }
        public string District { get; set; }
        public string Adress { get; set; }
        public string Email { get; set; }
    }
}
