//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnMuhasebeUygulamasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankTransfer
    {
        public int BankTransferCode { get; set; }
        public Nullable<int> BankAccountNo { get; set; }
        public string BankName { get; set; }
        public Nullable<int> CurrentCode { get; set; }
        public string CurrentName { get; set; }
        public Nullable<System.DateTime> BankTransferDate { get; set; }
        public string BankDescript { get; set; }
        public Nullable<double> BankTransferPrice { get; set; }
        public Nullable<double> BankExpencePrice { get; set; }
        public Nullable<int> BankExpencePercent { get; set; }
    }
}
