//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnMuhasebeUygulamasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        public int BankAccountNo { get; set; }
        public string IbanNo { get; set; }
        public string BankName { get; set; }
        public string BankAccountName { get; set; }
        public string BankBranch { get; set; }
        public string BankAccountHolder { get; set; }
        public string BankAccountHolderAdress { get; set; }
        public string BankAccountHolderPhone { get; set; }
        public Nullable<double> BankBalance { get; set; }
        public string Currency { get; set; }
    }
}
