//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnMuhasebeUygulamasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillDetail
    {
        public int BillDetailID { get; set; }
        public int BillCode { get; set; }
        public string LineType { get; set; }
        public Nullable<decimal> StockBarcode { get; set; }
        public Nullable<int> StockCode { get; set; }
        public string Discript { get; set; }
        public string UnitType { get; set; }
        public Nullable<int> IncomingAmount { get; set; }
        public Nullable<int> Yield { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<double> LineTotalAmount { get; set; }
        public Nullable<double> KdvPercent { get; set; }
        public Nullable<double> DiscountPercent { get; set; }
    
        public virtual Bill Bill { get; set; }
    }
}
