//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnMuhasebeUygulamasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChestProcess
    {
        public int RankNo { get; set; }
        public string ProcessType { get; set; }
        public Nullable<System.DateTime> Datee { get; set; }
        public string CurrentName { get; set; }
        public Nullable<decimal> BalanceDebt { get; set; }
        public Nullable<decimal> BalanceCredit { get; set; }
        public string Currency { get; set; }
        public string Descript { get; set; }
    }
}
