//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnMuhasebeUygulamasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chest
    {
        public int RankNo { get; set; }
        public Nullable<int> ChestCode { get; set; }
        public string ChestName { get; set; }
        public string Descript { get; set; }
        public Nullable<decimal> Incoming { get; set; }
        public Nullable<decimal> Outgoing { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string Currency { get; set; }
    }
}
