//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnMuhasebeUygulamasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int CompanyID { get; set; }
        public string CompanyTitle { get; set; }
        public string TaxOffice { get; set; }
        public Nullable<int> TaxNo { get; set; }
        public string Adress { get; set; }
        public string PhoneNo1 { get; set; }
        public string PhoneNo2 { get; set; }
    }
}
