//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnMuhasebeUygulamasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentCard
    {
        public string CurrentType { get; set; }
        public int CurrentCode { get; set; }
        public string CurrentName { get; set; }
        public Nullable<double> BalanceDebt { get; set; }
        public Nullable<double> BalanceCredit { get; set; }
        public string Currency { get; set; }
    
        public virtual CurrentCardDetail CurrentCardDetail { get; set; }
    }
}
