//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnMuhasebeUygulamasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentCardDetail
    {
        public int CurrentCode { get; set; }
        public string FirstInformation { get; set; }
        public string SecondInformation { get; set; }
        public string FirstPhone { get; set; }
        public string SecondPhone { get; set; }
        public string FaxNo { get; set; }
        public string GsmNo { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Province { get; set; }
        public string District { get; set; }
        public string Notes { get; set; }
    
        public virtual CurrentCard CurrentCard { get; set; }
    }
}
