//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnMuhasebeUygulamasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDetail
    {
        public int DetailsID { get; set; }
        public Nullable<int> TCIdentificationNumber { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeSurname { get; set; }
        public Nullable<int> EmployeeAge { get; set; }
        public string Adress { get; set; }
        public string Department { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<int> EmployeeID { get; set; }
    }
}
