//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnMuhasebeUygulamasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public string Statuss { get; set; }
        public int OrderCode { get; set; }
        public string Descript { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> ChargedAmount { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> ReadyAmount { get; set; }
        public Nullable<decimal> PendingAmount { get; set; }
    }
}
