//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnMuhasebeUygulamasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payroll
    {
        public int SequenceNo { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public string ProcessType { get; set; }
        public Nullable<int> CurrentCode { get; set; }
        public string CurrentName { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string BankName { get; set; }
    }
}
