//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnMuhasebeUygulamasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RateTable
    {
        public int RateID { get; set; }
        public string Symbol { get; set; }
        public string ShortName { get; set; }
        public string Descript { get; set; }
        public Nullable<decimal> FreeMarket { get; set; }
        public Nullable<decimal> CentralBank { get; set; }
    }
}
