//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnMuhasebeUygulamasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockMovement
    {
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public string ProcessType { get; set; }
        public int FreightbillNo { get; set; }
        public Nullable<int> CurrentCode { get; set; }
        public string CurrentName { get; set; }
        public Nullable<int> StockCode { get; set; }
        public Nullable<int> IncomingAmount { get; set; }
        public Nullable<int> Yield { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public Nullable<double> Discount { get; set; }
        public int SequanceNo { get; set; }
    
        public virtual Stock Stock { get; set; }
    }
}
