//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnMuhasebeUygulamasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stock()
        {
            this.StockMovements = new HashSet<StockMovement>();
        }
    
        public int StockCode { get; set; }
        public Nullable<decimal> StockBarcode { get; set; }
        public string StockName { get; set; }
        public string StockComment { get; set; }
        public string StockType { get; set; }
        public Nullable<double> StockKDV { get; set; }
        public string StockMainUnitType { get; set; }
        public string StockSecondUnitType { get; set; }
        public string StockThirdUnitType { get; set; }
        public Nullable<int> StockMainUnit { get; set; }
        public Nullable<int> StockSecondUnit { get; set; }
        public Nullable<int> StockThirdUnit { get; set; }
        public string StockKDVSalesStatus { get; set; }
        public string StockKDVBuyingStatus { get; set; }
        public Nullable<double> StockMainUnitSalesPrice { get; set; }
        public Nullable<double> StockSecondUnitSalesPrice { get; set; }
        public Nullable<double> StockThirdUnitSalesPrice { get; set; }
        public Nullable<double> StockMainUnitBuyingPrice { get; set; }
        public Nullable<double> StockSecondUnitBuyingPrice { get; set; }
        public Nullable<double> StockThirdUnitBuyingPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockMovement> StockMovements { get; set; }
    }
}
